# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:47:33+00:00



import argparse
import json
import os
from typing import *

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyHeader, APIKeyQuery, BaseSecurity
from fastapi import Path

from models import (
    FieldFormatDfsSlatesByDateDateGetResponse,
    FieldFormatInjuredPlayersCompetitionGetResponse,
    FieldFormatPlayerGameProjectionStatsByCompetitionCompetitionDateGetResponse,
    FieldFormatPlayerGameProjectionStatsByDateDateGetResponse,
    FieldFormatPlayerGameProjectionStatsByPlayerDatePlayeridGetResponse,
    FieldFormatUpcomingDfsSlatesByCompetitionCompetitionIdGetResponse,
    Format,
    Format1,
    Format5,
)

app = MCPProxy(
    contact={'x-twitter': 'nfldata'},
    title='Soccer v3 Projections',
    version='1.0',
    servers=[
        {'url': 'http://azure-api.sportsdata.io/v3/soccer/projections'},
        {'url': 'https://azure-api.sportsdata.io/v3/soccer/projections'},
    ],
)


@app.get(
    '/{format}/DfsSlatesByDate/{date}',
    tags=['dfs_slates_management'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def dfs_slates_by_date(format: Format, date: str = ...):
    """
    Dfs Slates By Date
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/InjuredPlayers/{competition}',
    description=""" This endpoint provides all currently injured soccer players by competition, along with injury details. """,
    tags=['injury_report_management', 'dfs_slates_management'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def injured_players_by_competition(format: Format1 = 'xml', competition: str = ...):
    """
    Injured Players By Competition
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/PlayerGameProjectionStatsByCompetition/{competition}/{date}',
    tags=['dfs_slates_management', 'player_statistics_projection'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def projected_player_game_stats_by_competition_w_dfs_salaries(
    format: Format1 = 'xml', competition: str = ..., date: str = ...
):
    """
    Projected Player Game Stats by Competition (w/ DFS Salaries)
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/PlayerGameProjectionStatsByDate/{date}',
    tags=['dfs_slates_management', 'player_statistics_projection'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def projected_player_game_stats_by_date_w_dfs_salaries(
    format: Format1 = 'xml', date: str = ...
):
    """
    Projected Player Game Stats by Date (w/ DFS Salaries)
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/PlayerGameProjectionStatsByPlayer/{date}/{playerid}',
    tags=['player_statistics_projection', 'dfs_slates_management'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def projected_player_game_stats_by_player_w_dfs_salaries(
    format: Format1 = 'xml', date: str = ..., playerid: str = ...
):
    """
    Projected Player Game Stats by Player (w/ DFS Salaries)
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/UpcomingDfsSlatesByCompetition/{competitionId}',
    tags=['dfs_slates_management'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def upcoming_dfs_slates_by_competition(
    format: Format5, competition_id: str = Path(..., alias='competitionId')
):
    """
    Upcoming Dfs Slates By Competition
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
