# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:47:33+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, RootModel


class DfsSlatePlayer(BaseModel):
    OperatorPlayerID: Optional[str] = None
    OperatorPlayerName: Optional[str] = None
    OperatorPosition: Optional[str] = None
    OperatorRosterSlots: Optional[List[str]] = None
    OperatorSalary: Optional[int] = None
    OperatorSlatePlayerID: Optional[str] = None
    PlayerGameProjectionStatID: Optional[int] = None
    PlayerID: Optional[int] = None
    RemovedByOperator: Optional[bool] = None
    SlateGameID: Optional[int] = None
    SlateID: Optional[int] = None
    SlatePlayerID: Optional[int] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None


class Player(BaseModel):
    BirthCity: Optional[str] = None
    BirthCountry: Optional[str] = None
    BirthDate: Optional[str] = None
    CommonName: Optional[str] = None
    DraftKingsPosition: Optional[str] = None
    FirstName: Optional[str] = None
    Foot: Optional[str] = None
    Gender: Optional[str] = None
    Height: Optional[int] = None
    InjuryBodyPart: Optional[str] = None
    InjuryNotes: Optional[str] = None
    InjuryStartDate: Optional[str] = None
    InjuryStatus: Optional[str] = None
    Jersey: Optional[int] = None
    LastName: Optional[str] = None
    Nationality: Optional[str] = None
    PhotoUrl: Optional[str] = None
    PlayerId: Optional[int] = None
    Position: Optional[str] = None
    PositionCategory: Optional[str] = None
    RotoWirePlayerID: Optional[int] = None
    ShortName: Optional[str] = None
    Updated: Optional[str] = None
    UsaTodayHeadshotNoBackgroundUpdated: Optional[str] = None
    UsaTodayHeadshotNoBackgroundUrl: Optional[str] = None
    UsaTodayHeadshotUpdated: Optional[str] = None
    UsaTodayHeadshotUrl: Optional[str] = None
    UsaTodayPlayerID: Optional[int] = None
    Weight: Optional[int] = None


class PlayerGameProjection(BaseModel):
    Assists: Optional[float] = None
    BlockedShots: Optional[float] = None
    Captain: Optional[bool] = None
    CornersWon: Optional[float] = None
    Crosses: Optional[float] = None
    DateTime: Optional[str] = None
    Day: Optional[str] = None
    DefenderCleanSheets: Optional[float] = None
    DraftKingsPosition: Optional[str] = None
    DraftKingsSalary: Optional[int] = None
    FanDuelPosition: Optional[str] = None
    FanDuelSalary: Optional[int] = None
    FantasyPoints: Optional[float] = None
    FantasyPointsDraftKings: Optional[float] = None
    FantasyPointsFanDuel: Optional[float] = None
    FantasyPointsMondogoal: Optional[float] = None
    FantasyPointsYahoo: Optional[float] = None
    Fouled: Optional[float] = None
    Fouls: Optional[float] = None
    GameId: Optional[int] = None
    Games: Optional[int] = None
    GlobalGameId: Optional[int] = None
    GlobalOpponentId: Optional[int] = None
    GlobalTeamId: Optional[int] = None
    GoalkeeperCleanSheets: Optional[float] = None
    GoalkeeperGoalsAgainst: Optional[float] = None
    GoalkeeperSaves: Optional[float] = None
    GoalkeeperSingleGoalAgainst: Optional[float] = None
    GoalkeeperWins: Optional[float] = None
    Goals: Optional[float] = None
    HomeOrAway: Optional[str] = None
    InjuryBodyPart: Optional[str] = None
    InjuryNotes: Optional[str] = None
    InjuryStartDate: Optional[str] = None
    InjuryStatus: Optional[str] = None
    Interceptions: Optional[float] = None
    IsGameOver: Optional[bool] = None
    Jersey: Optional[int] = None
    LastManTackle: Optional[float] = None
    Minutes: Optional[float] = None
    MondogoalPosition: Optional[str] = None
    MondogoalSalary: Optional[int] = None
    Name: Optional[str] = None
    Offsides: Optional[float] = None
    Opponent: Optional[str] = None
    OpponentId: Optional[int] = None
    OpponentScore: Optional[float] = None
    OwnGoals: Optional[float] = None
    Passes: Optional[float] = None
    PassesCompleted: Optional[float] = None
    PenaltiesConceded: Optional[float] = None
    PenaltiesWon: Optional[float] = None
    PenaltyKickGoals: Optional[float] = None
    PenaltyKickMisses: Optional[float] = None
    PenaltyKickSaves: Optional[float] = None
    PlayerId: Optional[int] = None
    Position: Optional[str] = None
    PositionCategory: Optional[str] = None
    RedCards: Optional[float] = None
    RoundId: Optional[int] = None
    Score: Optional[float] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    ShortName: Optional[str] = None
    Shots: Optional[float] = None
    ShotsOnGoal: Optional[float] = None
    Started: Optional[int] = None
    StatId: Optional[int] = None
    Suspension: Optional[bool] = None
    SuspensionReason: Optional[str] = None
    Tackles: Optional[float] = None
    TacklesWon: Optional[float] = None
    Team: Optional[str] = None
    TeamId: Optional[int] = None
    Touches: Optional[float] = None
    Updated: Optional[str] = None
    UpdatedUtc: Optional[str] = None
    YahooPosition: Optional[str] = None
    YahooSalary: Optional[int] = None
    YellowCards: Optional[float] = None
    YellowRedCards: Optional[float] = None


class PlayoffAggregateScore(BaseModel):
    Created: Optional[str] = None
    TeamA_AggregateScore: Optional[int] = None
    TeamA_Id: Optional[int] = None
    TeamB_AggregateScore: Optional[int] = None
    TeamB_Id: Optional[int] = None
    Updated: Optional[str] = None
    WinningTeamId: Optional[int] = None


class Format(Enum):
    json = 'json'
    xml = 'xml'


class FieldFormatInjuredPlayersCompetitionGetResponse(RootModel[List[Player]]):
    root: List[Player]


class Format1(Enum):
    xml = 'xml'
    json = 'json'


class FieldFormatPlayerGameProjectionStatsByCompetitionCompetitionDateGetResponse(
    RootModel[List[PlayerGameProjection]]
):
    root: List[PlayerGameProjection]


class FieldFormatPlayerGameProjectionStatsByDateDateGetResponse(
    RootModel[List[PlayerGameProjection]]
):
    root: List[PlayerGameProjection]


class FieldFormatPlayerGameProjectionStatsByPlayerDatePlayeridGetResponse(
    RootModel[List[PlayerGameProjection]]
):
    root: List[PlayerGameProjection]


class Format5(Enum):
    json = 'json'
    xml = 'xml'


class Game(BaseModel):
    Attendance: Optional[int] = None
    AwayTeamCountryCode: Optional[str] = None
    AwayTeamFormation: Optional[str] = None
    AwayTeamId: Optional[int] = None
    AwayTeamKey: Optional[str] = None
    AwayTeamMoneyLine: Optional[int] = None
    AwayTeamName: Optional[str] = None
    AwayTeamPointSpreadPayout: Optional[int] = None
    AwayTeamScore: Optional[int] = None
    AwayTeamScoreExtraTime: Optional[int] = None
    AwayTeamScorePenalty: Optional[int] = None
    AwayTeamScorePeriod1: Optional[int] = None
    AwayTeamScorePeriod2: Optional[int] = None
    Clock: Optional[int] = None
    ClockDisplay: Optional[str] = None
    ClockExtra: Optional[int] = None
    DateTime: Optional[str] = None
    Day: Optional[str] = None
    DrawMoneyLine: Optional[int] = None
    GameId: Optional[int] = None
    GlobalAwayTeamId: Optional[int] = None
    GlobalGameId: Optional[int] = None
    GlobalHomeTeamId: Optional[int] = None
    Group: Optional[str] = None
    HomeTeamCountryCode: Optional[str] = None
    HomeTeamFormation: Optional[str] = None
    HomeTeamId: Optional[int] = None
    HomeTeamKey: Optional[str] = None
    HomeTeamMoneyLine: Optional[int] = None
    HomeTeamName: Optional[str] = None
    HomeTeamPointSpreadPayout: Optional[int] = None
    HomeTeamScore: Optional[int] = None
    HomeTeamScoreExtraTime: Optional[int] = None
    HomeTeamScorePenalty: Optional[int] = None
    HomeTeamScorePeriod1: Optional[int] = None
    HomeTeamScorePeriod2: Optional[int] = None
    IsClosed: Optional[bool] = None
    OverPayout: Optional[int] = None
    OverUnder: Optional[float] = None
    Period: Optional[str] = None
    PlayoffAggregateScore_1: Optional[PlayoffAggregateScore] = Field(
        None, alias='PlayoffAggregateScore'
    )
    PointSpread: Optional[float] = None
    RoundId: Optional[int] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    Status: Optional[str] = None
    UnderPayout: Optional[int] = None
    Updated: Optional[str] = None
    UpdatedUtc: Optional[str] = None
    VenueId: Optional[int] = None
    VenueType: Optional[str] = None
    Week: Optional[int] = None
    Winner: Optional[str] = None


class DfsSlateGame(BaseModel):
    Game_1: Optional[Game] = Field(None, alias='Game')
    GameID: Optional[int] = None
    OperatorGameID: Optional[int] = None
    RemovedByOperator: Optional[bool] = None
    SlateGameID: Optional[int] = None
    SlateID: Optional[int] = None


class DfsSlate(BaseModel):
    CompetitionId: Optional[int] = None
    DfsSlateGames: Optional[List[DfsSlateGame]] = None
    DfsSlatePlayers: Optional[List[DfsSlatePlayer]] = None
    IsMultiDaySlate: Optional[bool] = None
    NumberOfGames: Optional[int] = None
    Operator: Optional[str] = None
    OperatorDay: Optional[str] = None
    OperatorGameType: Optional[str] = None
    OperatorName: Optional[str] = None
    OperatorSlateID: Optional[int] = None
    OperatorStartTime: Optional[str] = None
    RemovedByOperator: Optional[bool] = None
    SalaryCap: Optional[int] = None
    SlateID: Optional[int] = None
    SlateRosterSlots: Optional[List[str]] = None


class FieldFormatDfsSlatesByDateDateGetResponse(RootModel[List[DfsSlate]]):
    root: List[DfsSlate]


class FieldFormatUpcomingDfsSlatesByCompetitionCompetitionIdGetResponse(
    RootModel[List[DfsSlate]]
):
    root: List[DfsSlate]
